name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none

      - name: Install composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests
